language: csharp
mono: none
sudo: false
dotnet: 3.1
dist: bionic

script:
  # somehow, just running the "dotnet test" here normally is responsible for
  # tests timing out when (and only when) run for PR builds, when (and only
  # when) the PR is coming from a fork of the project.  even weirder, running
  # the tests in a background process and then waiting seems to work around
  # the issue.  hopefully we can figure this out eventually, but I don't want
  # it to discourage contributors in the meantime (airbreather 2019-09-12).
  - dotnet build -c Release -v minimal -p:WarningLevel=3
  - dotnet test  -c Release --no-build --filter '(TestCategory!=LongRunning)&(TestCategory!=Stress)&(TestCategory!=FailureCase)'&
  - wait $!
  - dotnet pack  -c Release --no-build -p:NoWarn=NU5105


deploy:


  - on:
      branch: master
    provider: script
    script:
      - dotnet nuget push **/*.nupkg -s https://api.nuget.org/v3/index.json -k $NUGET_API_KEY
    skip_cleanup: true


  - on:
      branch: develop
    provider: script
    script:
      - dotnet nuget push **/*.nupkg -s https://www.myget.org/F/nettopologysuite/api/v3/index.json -k $MYGET_API_KEY
    skip_cleanup: true


env:
  global:
  - secure: BKez53qv2J/UWqi4y6ryHKC4KoqBM7ss8xKgFOIL5y3/MTp7ooi4KbfN8r6BXG2fe8bDTdfM11oI694rAILoYH8L81XrxZ1vTEJ3DNa9WnYtHfAYkFPkGw0QSvnYYKMoQoOAHGW++lYwz14YVA63nkj3UCGOrkp4qzo3s+NH/UI=
  - secure: XQH0+iF8k+nzSC1UFQ/4Zy+6KyJ/wzrH79e3n/ZHI2MecahlA/YVL8LlW1CRNoIYxOTypjgxXwkMj/CRi5jyYH84RZIeBrOTqG1XbiryL4BcTFuI398Xqc86iHF22//p8/rFVCdb/R1i0yEGR/NWPLuOHX8gyv1bQj0mCg+Ec6o=

